### ISSUE TITLE
Large inputs can exceed memory_limit

### ISSUE THREAD

**Issue by elazar** [chrismou/phergie-irc-plugin-react-dice#2]
Issuing this command against the Phergie v3 instance on Freenode...

```
!dice 10000000 10000000
```

... causes this error...

```
[30-Apr-2015 16:25:04 America/Chicago] PHP Fatal error:  Allowed memory size of 134217728 bytes exhausted (tried to allocate 32 bytes) in /home/mturland/phergie-freenode/vendor/chrismou/phergie-irc-plugin-react-dice/src/Plugin.php on line 105
```

[Here](https://github.com/chrismou/phergie-irc-plugin-react-dice/blob/c9d2cd5bef8c15606e0af974a25b026debc82c85/src/Plugin.php#L105) is the cited line. `Plugin->handleCommand()` should probably sanity check its roll count by comparing the return value of [`memory_get_usage()`](http://php.net/manual/en/function.memory-get-usage.php) against the return value of `ini_get('memory_limit')` on each loop iteration to ensure that the current roll won't cause `memory_limit` to be exceeded.

**Comment by chrismou** [comment]
Do you know if irc has a max character limit for a message?

**Comment by elazar** [comment]
It does, but it's difficult to account for how much of that any given message is going to use because of prefixes and such. After further discussion, it may just be safer to have some reasonable upper bounds (e.g. `100` or `1000`), perhaps that can be overridden by configuration.

**Comment by chrismou** [comment]
That was my thinking. I'll get this sorted this weekend, cheers for the heads up.

**Comment by chrismou** [comment]
I've added a few limits that can be overridden via config. The numbers are low enough that by default it should be OK.

I just need to update a few tests and I'll get it tagged

**Comment by chrismou** [comment]
Tag 1.0.2 released

**Comment by elazar** [comment]
Think you [added Pong and AutoJoin](https://github.com/chrismou/phergie-irc-plugin-react-dice/commit/6700a91c9076da602e0bb4f767d5db6fa58d434b#diff-b5d0ee8c97c7abd7e3fa29b9a27d1780R24) for testing and forgot to take them out.

**Comment by chrismou** [comment]
You're right - though that was on the AudioScrobbler plugin!

**Comment by elazar** [comment]
Appears it was on both. :p I need to come up with a better recommended setup for plugin developers.

**Comment by chrismou** [comment]
Am I going crazy? I don't see it on this repo

**Comment by elazar** [comment]
Ah, OK, looks like you removed them in [a subsequent commit](https://github.com/chrismou/phergie-irc-plugin-react-dice/commit/ae9488789bb9d332a727b988c0585e76e239fed5).
